# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14xWdzCVLKj2FzEhFET49aNsl28WY5wfm
"""

import os
import requests
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

def run_prediction():
    try:
        # โหลดไฟล์ Excel จากโฟลเดอร์เดียวกัน (สามารถปรับเปลี่ยนเป็นการดึงข้อมูลอัตโนมัติประจำวันได้ที่นี่)
        file_path = "B-INNOTECHRMF_Daily_NAV_5Years.xlsx"
        df = pd.read_excel(file_path, sheet_name="Daily NAV Data", skiprows=2)
        df.columns = ['Date', 'NAV', 'Daily Return']
        df['Date'] = pd.to_datetime(df['Date'])
        df = df.dropna().sort_values('Date').reset_index(drop=True)

        # Feature Engineering
        df['MA_5'] = df['NAV'].rolling(window=5).mean()
        df['MA_20'] = df['NAV'].rolling(window=20).mean()
        df['Volatility_5'] = df['NAV'].rolling(window=5).std()
        df['Volatility_20'] = df['NAV'].rolling(window=20).std()

        delta = df['NAV'].diff()
        gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
        rs = gain / loss
        df['RSI'] = 100 - (100 / (1 + rs))

        df['Target_1d'] = (df['NAV'].shift(-1) > df['NAV']).astype(int)
        df['Target_7d'] = (df['NAV'].shift(-7) > df['NAV']).astype(int)

        df_model = df.dropna().reset_index(drop=True)
        features = ['NAV', 'Daily Return', 'MA_5', 'MA_20', 'Volatility_5', 'Volatility_20', 'RSI']
        X = df_model[features].values
        y1 = df_model['Target_1d'].values
        y7 = df_model['Target_7d'].values

        # แบ่งข้อมูลสำหรับ Train และ Test เพื่อวัดค่า % Accuracy
        X_train, X_test, y1_train, y1_test, y7_train, y7_test = train_test_split(
            X, y1, y7, test_size=0.2, shuffle=False
        )

        # Scale ข้อมูล
        scaler = StandardScaler()
        X_train_scaled = scaler.fit_transform(X_train)
        X_test_scaled = scaler.transform(X_test)

        # สำหรับทำนายข้อมูลล่าสุด (ใช้ข้อมูลทั้งหมด Scale ร่วมกัน)
        X_all_scaled = scaler.fit_transform(X)

        # ML Model (1 วัน)
        model_1d = GradientBoostingClassifier(n_estimators=150, learning_rate=0.01, max_depth=3, random_state=42)
        model_1d.fit(X_train_scaled, y1_train)
        preds_1d_test = model_1d.predict(X_test_scaled)
        acc_1d = accuracy_score(y1_test, preds_1d_test) * 100

        # ML Model (7 วัน)
        model_7d = GradientBoostingClassifier(n_estimators=150, learning_rate=0.01, max_depth=3, random_state=42)
        model_7d.fit(X_train_scaled, y7_train)
        preds_7d_test = model_7d.predict(X_test_scaled)
        acc_7d = accuracy_score(y7_test, preds_7d_test) * 100

        # เทรนโมเดลด้วยข้อมูลทั้งหมดเพื่อใช้ทำนายผลลัพธ์ปัจจุบัน
        model_1d.fit(X_all_scaled, y1)
        model_7d.fit(X_all_scaled, y7)

        # ทำนายข้อมูลล่าสุด
        latest_features = X_all_scaled[-1:]
        pred_1d = model_1d.predict(latest_features)[0]
        pred_7d = model_7d.predict(latest_features)[0]
        latest_nav = df_model['NAV'].iloc[-1]
        latest_date = df_model['Date'].iloc[-1].strftime('%Y-%m-%d')

        # ข้อความแจ้งเตือน
        status_1d = "📈 ขาขึ้น (UP)" if pred_1d == 1 else "📉 ขาลง (DOWN)"
        status_7d = "📈 ขาขึ้น (UP)" if pred_7d == 1 else "📉 ขาลง (DOWN)"

        message = f"""🤖 รายงานอัตโนมัติ: B-INNOTECHRMF
📅 ข้อมูลวันที่: {latest_date}
💰 NAV ล่าสุด: {latest_nav:,.4f} THB

🔮 ผลการทำนาย:
- แนวโน้มวันรุ่งขึ้น (1 วัน): {status_1d}
- แนวโน้มอีก 7 วันข้างหน้า: {status_7d}

📊 ความแม่นยำของโมเดล (Accuracy):
- โมเดล 1 วัน: {acc_1d:.2f}%
- โมเดล 7 วัน: {acc_7d:.2f}%"""

        # ส่งข้อความผ่าน LINE Messaging API (Push Message)
        line_token = os.environ.get('LINE_CHANNEL_ACCESS_TOKEN')
        line_user_id = os.environ.get('LINE_USER_ID')

        url = "https://api.line.me/v2/bot/message/push"
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {line_token}"
        }
        payload = {
            "to": line_user_id,
            "messages": [
                {
                    "type": "text",
                    "text": message.strip()
                }
            ]
        }

        response = requests.post(url, headers=headers, json=payload)

        print("Response status:", response.status_code)
        print("Response body:", response.text)

        if response.status_code == 200:
            print("Successfully sent message to LINE!")
        else:
            print("Failed to send message to LINE.")

    except Exception as e:
        print(f"Error: {str(e)}")

if __name__ == "__main__":
    run_prediction()