# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14xWdzCVLKj2FzEhFET49aNsl28WY5wfm
"""

import os
import requests
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingClassifier

def run_prediction():
    try:
        # โหลดไฟล์ Excel จากโฟลเดอร์เดียวกันใน Hugging Face Repo
        file_path = "B-INNOTECHRMF_Daily_NAV_5Years.xlsx"
        df = pd.read_excel(file_path, sheet_name="Daily NAV Data", skiprows=2)
        df.columns = ['Date', 'NAV', 'Daily Return']
        df['Date'] = pd.to_datetime(df['Date'])
        df = df.dropna().sort_values('Date').reset_index(drop=True)

        # Feature Engineering
        df['MA_5'] = df['NAV'].rolling(window=5).mean()
        df['MA_20'] = df['NAV'].rolling(window=20).mean()
        df['Volatility_5'] = df['NAV'].rolling(window=5).std()
        df['Volatility_20'] = df['NAV'].rolling(window=20).std()

        delta = df['NAV'].diff()
        gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
        rs = gain / loss
        df['RSI'] = 100 - (100 / (1 + rs))

        df['Target_1d'] = (df['NAV'].shift(-1) > df['NAV']).astype(int)
        df['Target_7d'] = (df['NAV'].shift(-7) > df['NAV']).astype(int)

        df_model = df.dropna().reset_index(drop=True)
        features = ['NAV', 'Daily Return', 'MA_5', 'MA_20', 'Volatility_5', 'Volatility_20', 'RSI']
        X = df_model[features].values
        y1 = df_model['Target_1d'].values
        y7 = df_model['Target_7d'].values

        # ML Model (Gradient Boosting)
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X)

        model_1d = GradientBoostingClassifier(n_estimators=150, learning_rate=0.01, max_depth=3, random_state=42)
        model_1d.fit(X_scaled, y1)

        model_7d = GradientBoostingClassifier(n_estimators=150, learning_rate=0.01, max_depth=3, random_state=42)
        model_7d.fit(X_scaled, y7)

        # ทำนายข้อมูลล่าสุด
        latest_features = X_scaled[-1:]
        pred_1d = model_1d.predict(latest_features)[0]
        pred_7d = model_7d.predict(latest_features)[0]
        latest_nav = df_model['NAV'].iloc[-1]
        latest_date = df_model['Date'].iloc[-1].strftime('%Y-%m-%d')

        # ข้อความแจ้งเตือน
        status_1d = "📈 ขาขึ้น (UP)" if pred_1d == 1 else "📉 ขาลง (DOWN)"
        status_7d = "📈 ขาขึ้น (UP)" if pred_7d == 1 else "📉 ขาลง (DOWN)"

        message = f"""
🤖 รายงานอัตโนมัติ: B-INNOTECHRMF
📅 ข้อมูลวันที่: {latest_date}
💰 NAV ล่าสุด: {latest_nav:,.4f} THB

🔮 ผลการทำนาย:
- แนวโน้มวันรุ่งขึ้น (1 วัน): {status_1d}
- แนวโน้มอีก 7 วันข้างหน้า: {status_7d}
"""

        # ดึง Token จาก Environment Variable เพื่อความปลอดภัย
        line_token = os.environ.get('LINE_NOTIFY_TOKEN')
        headers = {'Authorization': 'Bearer ' + line_token}
        requests.post('https://notify-api.line.me/api/notify', headers=headers, data={'message': message})
        print("Successfully sent message to LINE!")

    except Exception as e:
        print(f"Error: {str(e)}")

if __name__ == "__main__":
    run_prediction()